export const countries = [
  { name: "Afghanistan", dial_code: "+93", iso2: "af", flagUrl: "https://flagcdn.com/af.svg" },
  { name: "Albania", dial_code: "+355", iso2: "al", flagUrl: "https://flagcdn.com/al.svg" },
  { name: "Algeria", dial_code: "+213", iso2: "dz", flagUrl: "https://flagcdn.com/dz.svg" },
  { name: "Andorra", dial_code: "+376", iso2: "ad", flagUrl: "https://flagcdn.com/ad.svg" },
  { name: "Angola", dial_code: "+244", iso2: "ao", flagUrl: "https://flagcdn.com/ao.svg" },
  { name: "Argentina", dial_code: "+54", iso2: "ar", flagUrl: "https://flagcdn.com/ar.svg" },
  { name: "Armenia", dial_code: "+374", iso2: "am", flagUrl: "https://flagcdn.com/am.svg" },
  { name: "Australia", dial_code: "+61", iso2: "au", flagUrl: "https://flagcdn.com/au.svg" },
  { name: "Austria", dial_code: "+43", iso2: "at", flagUrl: "https://flagcdn.com/at.svg" },
  { name: "Azerbaijan", dial_code: "+994", iso2: "az", flagUrl: "https://flagcdn.com/az.svg" },
  { name: "Bahamas", dial_code: "+1-242", iso2: "bs", flagUrl: "https://flagcdn.com/bs.svg" },
  { name: "Bahrain", dial_code: "+973", iso2: "bh", flagUrl: "https://flagcdn.com/bh.svg" },
  { name: "Bangladesh", dial_code: "+880", iso2: "bd", flagUrl: "https://flagcdn.com/bd.svg" },
  { name: "Barbados", dial_code: "+1-246", iso2: "bb", flagUrl: "https://flagcdn.com/bb.svg" },
  { name: "Belarus", dial_code: "+375", iso2: "by", flagUrl: "https://flagcdn.com/by.svg" },
  { name: "Belgium", dial_code: "+32", iso2: "be", flagUrl: "https://flagcdn.com/be.svg" },
  { name: "Belize", dial_code: "+501", iso2: "bz", flagUrl: "https://flagcdn.com/bz.svg" },
  { name: "Benin", dial_code: "+229", iso2: "bj", flagUrl: "https://flagcdn.com/bj.svg" },
  { name: "Bhutan", dial_code: "+975", iso2: "bt", flagUrl: "https://flagcdn.com/bt.svg" },
  { name: "Bolivia", dial_code: "+591", iso2: "bo", flagUrl: "https://flagcdn.com/bo.svg" },
  { name: "Bosnia and Herzegovina", dial_code: "+387", iso2: "ba", flagUrl: "https://flagcdn.com/ba.svg" },
  { name: "Botswana", dial_code: "+267", iso2: "bw", flagUrl: "https://flagcdn.com/bw.svg" },
  { name: "Brazil", dial_code: "+55", iso2: "br", flagUrl: "https://flagcdn.com/br.svg" },
  { name: "Brunei", dial_code: "+673", iso2: "bn", flagUrl: "https://flagcdn.com/bn.svg" },
  { name: "Bulgaria", dial_code: "+359", iso2: "bg", flagUrl: "https://flagcdn.com/bg.svg" },
  { name: "Burkina Faso", dial_code: "+226", iso2: "bf", flagUrl: "https://flagcdn.com/bf.svg" },
  { name: "Burundi", dial_code: "+257", iso2: "bi", flagUrl: "https://flagcdn.com/bi.svg" },
  { name: "Cambodia", dial_code: "+855", iso2: "kh", flagUrl: "https://flagcdn.com/kh.svg" },
  { name: "Cameroon", dial_code: "+237", iso2: "cm", flagUrl: "https://flagcdn.com/cm.svg" },
  { name: "Canada", dial_code: "+1", iso2: "ca", flagUrl: "https://flagcdn.com/ca.svg" },
  { name: "Cape Verde", dial_code: "+238", iso2: "cv", flagUrl: "https://flagcdn.com/cv.svg" },
  { name: "Central African Republic", dial_code: "+236", iso2: "cf", flagUrl: "https://flagcdn.com/cf.svg" },
  { name: "Chad", dial_code: "+235", iso2: "td", flagUrl: "https://flagcdn.com/td.svg" },
  { name: "Chile", dial_code: "+56", iso2: "cl", flagUrl: "https://flagcdn.com/cl.svg" },
  { name: "China", dial_code: "+86", iso2: "cn", flagUrl: "https://flagcdn.com/cn.svg" },
  { name: "Colombia", dial_code: "+57", iso2: "co", flagUrl: "https://flagcdn.com/co.svg" },
  { name: "Comoros", dial_code: "+269", iso2: "km", flagUrl: "https://flagcdn.com/km.svg" },
  { name: "Congo (DRC)", dial_code: "+243", iso2: "cd", flagUrl: "https://flagcdn.com/cd.svg" },
  { name: "Congo (Republic)", dial_code: "+242", iso2: "cg", flagUrl: "https://flagcdn.com/cg.svg" },
  { name: "Costa Rica", dial_code: "+506", iso2: "cr", flagUrl: "https://flagcdn.com/cr.svg" },
  { name: "Croatia", dial_code: "+385", iso2: "hr", flagUrl: "https://flagcdn.com/hr.svg" },
  { name: "Cuba", dial_code: "+53", iso2: "cu", flagUrl: "https://flagcdn.com/cu.svg" },
  { name: "Cyprus", dial_code: "+357", iso2: "cy", flagUrl: "https://flagcdn.com/cy.svg" },
  { name: "Czech Republic", dial_code: "+420", iso2: "cz", flagUrl: "https://flagcdn.com/cz.svg" },
  { name: "Denmark", dial_code: "+45", iso2: "dk", flagUrl: "https://flagcdn.com/dk.svg" },
  { name: "Djibouti", dial_code: "+253", iso2: "dj", flagUrl: "https://flagcdn.com/dj.svg" },
  { name: "Dominica", dial_code: "+1-767", iso2: "dm", flagUrl: "https://flagcdn.com/dm.svg" },
  { name: "Dominican Republic", dial_code: "+1-809", iso2: "do", flagUrl: "https://flagcdn.com/do.svg" },
  { name: "East Timor", dial_code: "+670", iso2: "tl", flagUrl: "https://flagcdn.com/tl.svg" },
  { name: "Ecuador", dial_code: "+593", iso2: "ec", flagUrl: "https://flagcdn.com/ec.svg" },
  { name: "Egypt", dial_code: "+20", iso2: "eg", flagUrl: "https://flagcdn.com/eg.svg" },
  { name: "El Salvador", dial_code: "+503", iso2: "sv", flagUrl: "https://flagcdn.com/sv.svg" },
  { name: "Equatorial Guinea", dial_code: "+240", iso2: "gq", flagUrl: "https://flagcdn.com/gq.svg" },
  { name: "Eritrea", dial_code: "+291", iso2: "er", flagUrl: "https://flagcdn.com/er.svg" },
  { name: "Estonia", dial_code: "+372", iso2: "ee", flagUrl: "https://flagcdn.com/ee.svg" },
  { name: "Eswatini", dial_code: "+268", iso2: "sz", flagUrl: "https://flagcdn.com/sz.svg" },
  { name: "Ethiopia", dial_code: "+251", iso2: "et", flagUrl: "https://flagcdn.com/et.svg" },
  { name: "Fiji", dial_code: "+679", iso2: "fj", flagUrl: "https://flagcdn.com/fj.svg" },
  { name: "Finland", dial_code: "+358", iso2: "fi", flagUrl: "https://flagcdn.com/fi.svg" },
  { name: "France", dial_code: "+33", iso2: "fr", flagUrl: "https://flagcdn.com/fr.svg" },
  { name: "Gabon", dial_code: "+241", iso2: "ga", flagUrl: "https://flagcdn.com/ga.svg" },
  { name: "Gambia", dial_code: "+220", iso2: "gm", flagUrl: "https://flagcdn.com/gm.svg" },
  { name: "Georgia", dial_code: "+995", iso2: "ge", flagUrl: "https://flagcdn.com/ge.svg" },
  { name: "Germany", dial_code: "+49", iso2: "de", flagUrl: "https://flagcdn.com/de.svg" },
  { name: "Ghana", dial_code: "+233", iso2: "gh", flagUrl: "https://flagcdn.com/gh.svg" },
  { name: "Greece", dial_code: "+30", iso2: "gr", flagUrl: "https://flagcdn.com/gr.svg" },
  { name: "Grenada", dial_code: "+1-473", iso2: "gd", flagUrl: "https://flagcdn.com/gd.svg" },
  { name: "Guatemala", dial_code: "+502", iso2: "gt", flagUrl: "https://flagcdn.com/gt.svg" },
  { name: "Guinea", dial_code: "+224", iso2: "gn", flagUrl: "https://flagcdn.com/gn.svg" },
  { name: "Guinea-Bissau", dial_code: "+245", iso2: "gw", flagUrl: "https://flagcdn.com/gw.svg" },
  { name: "Guyana", dial_code: "+592", iso2: "gy", flagUrl: "https://flagcdn.com/gy.svg" },
  { name: "Haiti", dial_code: "+509", iso2: "ht", flagUrl: "https://flagcdn.com/ht.svg" },
  { name: "Honduras", dial_code: "+504", iso2: "hn", flagUrl: "https://flagcdn.com/hn.svg" },
  { name: "Hungary", dial_code: "+36", iso2: "hu", flagUrl: "https://flagcdn.com/hu.svg" },
  { name: "Iceland", dial_code: "+354", iso2: "is", flagUrl: "https://flagcdn.com/is.svg" },
  { name: "India", dial_code: "+91", iso2: "in", flagUrl: "https://flagcdn.com/in.svg" },
  { name: "Indonesia", dial_code: "+62", iso2: "id", flagUrl: "https://flagcdn.com/id.svg" },
  { name: "Iran", dial_code: "+98", iso2: "ir", flagUrl: "https://flagcdn.com/ir.svg" },
  { name: "Iraq", dial_code: "+964", iso2: "iq", flagUrl: "https://flagcdn.com/iq.svg" },
  { name: "Ireland", dial_code: "+353", iso2: "ie", flagUrl: "https://flagcdn.com/ie.svg" },
  { name: "Israel", dial_code: "+972", iso2: "il", flagUrl: "https://flagcdn.com/il.svg" },
  { name: "Italy", dial_code: "+39", iso2: "it", flagUrl: "https://flagcdn.com/it.svg" },
  { name: "Ivory Coast", dial_code: "+225", iso2: "ci", flagUrl: "https://flagcdn.com/ci.svg" },
  { name: "Jamaica", dial_code: "+1-876", iso2: "jm", flagUrl: "https://flagcdn.com/jm.svg" },
  { name: "Japan", dial_code: "+81", iso2: "jp", flagUrl: "https://flagcdn.com/jp.svg" },
  { name: "Jordan", dial_code: "+962", iso2: "jo", flagUrl: "https://flagcdn.com/jo.svg" },
  { name: "Kazakhstan", dial_code: "+7", iso2: "kz", flagUrl: "https://flagcdn.com/kz.svg" },
  { name: "Kenya", dial_code: "+254", iso2: "ke", flagUrl: "https://flagcdn.com/ke.svg" },
  { name: "Kiribati", dial_code: "+686", iso2: "ki", flagUrl: "https://flagcdn.com/ki.svg" },
  { name: "Kuwait", dial_code: "+965", iso2: "kw", flagUrl: "https://flagcdn.com/kw.svg" },
  { name: "Kyrgyzstan", dial_code: "+996", iso2: "kg", flagUrl: "https://flagcdn.com/kg.svg" },
  { name: "Laos", dial_code: "+856", iso2: "la", flagUrl: "https://flagcdn.com/la.svg" },
  { name: "Latvia", dial_code: "+371", iso2: "lv", flagUrl: "https://flagcdn.com/lv.svg" },
  { name: "Lebanon", dial_code: "+961", iso2: "lb", flagUrl: "https://flagcdn.com/lb.svg" },
  { name: "Lesotho", dial_code: "+266", iso2: "ls", flagUrl: "https://flagcdn.com/ls.svg" },
  { name: "Liberia", dial_code: "+231", iso2: "lr", flagUrl: "https://flagcdn.com/lr.svg" },
  { name: "Libya", dial_code: "+218", iso2: "ly", flagUrl: "https://flagcdn.com/ly.svg" },
  { name: "Liechtenstein", dial_code: "+423", iso2: "li", flagUrl: "https://flagcdn.com/li.svg" },
  { name: "Lithuania", dial_code: "+370", iso2: "lt", flagUrl: "https://flagcdn.com/lt.svg" },
  { name: "Luxembourg", dial_code: "+352", iso2: "lu", flagUrl: "https://flagcdn.com/lu.svg" },
  { name: "Madagascar", dial_code: "+261", iso2: "mg", flagUrl: "https://flagcdn.com/mg.svg" },
  { name: "Malawi", dial_code: "+265", iso2: "mw", flagUrl: "https://flagcdn.com/mw.svg" },
  { name: "Malaysia", dial_code: "+60", iso2: "my", flagUrl: "https://flagcdn.com/my.svg" },
  { name: "Maldives", dial_code: "+960", iso2: "mv", flagUrl: "https://flagcdn.com/mv.svg" },
  { name: "Mali", dial_code: "+223", iso2: "ml", flagUrl: "https://flagcdn.com/ml.svg" },
  { name: "Malta", dial_code: "+356", iso2: "mt", flagUrl: "https://flagcdn.com/mt.svg" },
  { name: "Marshall Islands", dial_code: "+692", iso2: "mh", flagUrl: "https://flagcdn.com/mh.svg" },
  { name: "Mauritania", dial_code: "+222", iso2: "mr", flagUrl: "https://flagcdn.com/mr.svg" },
  { name: "Mauritius", dial_code: "+230", iso2: "mu", flagUrl: "https://flagcdn.com/mu.svg" },
  { name: "Mexico", dial_code: "+52", iso2: "mx", flagUrl: "https://flagcdn.com/mx.svg" },
  { name: "Micronesia", dial_code: "+691", iso2: "fm", flagUrl: "https://flagcdn.com/fm.svg" },
  { name: "Moldova", dial_code: "+373", iso2: "md", flagUrl: "https://flagcdn.com/md.svg" },
  { name: "Monaco", dial_code: "+377", iso2: "mc", flagUrl: "https://flagcdn.com/mc.svg" },
  { name: "Mongolia", dial_code: "+976", iso2: "mn", flagUrl: "https://flagcdn.com/mn.svg" },
  { name: "Montenegro", dial_code: "+382", iso2: "me", flagUrl: "https://flagcdn.com/me.svg" },
  { name: "Morocco", dial_code: "+212", iso2: "ma", flagUrl: "https://flagcdn.com/ma.svg" },
  { name: "Mozambique", dial_code: "+258", iso2: "mz", flagUrl: "https://flagcdn.com/mz.svg" },
  { name: "Myanmar", dial_code: "+95", iso2: "mm", flagUrl: "https://flagcdn.com/mm.svg" },
  { name: "Namibia", dial_code: "+264", iso2: "na", flagUrl: "https://flagcdn.com/na.svg" },
  { name: "Nauru", dial_code: "+674", iso2: "nr", flagUrl: "https://flagcdn.com/nr.svg" },
  { name: "Nepal", dial_code: "+977", iso2: "np", flagUrl: "https://flagcdn.com/np.svg" },
  { name: "Netherlands", dial_code: "+31", iso2: "nl", flagUrl: "https://flagcdn.com/nl.svg" },
  { name: "New Zealand", dial_code: "+64", iso2: "nz", flagUrl: "https://flagcdn.com/nz.svg" },
  { name: "Nicaragua", dial_code: "+505", iso2: "ni", flagUrl: "https://flagcdn.com/ni.svg" },
  { name: "Niger", dial_code: "+227", iso2: "ne", flagUrl: "https://flagcdn.com/ne.svg" },
  { name: "Nigeria", dial_code: "+234", iso2: "ng", flagUrl: "https://flagcdn.com/ng.svg" },
  { name: "North Korea", dial_code: "+850", iso2: "kp", flagUrl: "https://flagcdn.com/kp.svg" },
  { name: "North Macedonia", dial_code: "+389", iso2: "mk", flagUrl: "https://flagcdn.com/mk.svg" },
  { name: "Norway", dial_code: "+47", iso2: "no", flagUrl: "https://flagcdn.com/no.svg" },
  { name: "Oman", dial_code: "+968", iso2: "om", flagUrl: "https://flagcdn.com/om.svg" },
  { name: "Pakistan", dial_code: "+92", iso2: "pk", flagUrl: "https://flagcdn.com/pk.svg" },
  { name: "Palau", dial_code: "+680", iso2: "pw", flagUrl: "https://flagcdn.com/pw.svg" },
  { name: "Palestine", dial_code: "+970", iso2: "ps", flagUrl: "https://flagcdn.com/ps.svg" },
  { name: "Panama", dial_code: "+507", iso2: "pa", flagUrl: "https://flagcdn.com/pa.svg" },
  { name: "Papua New Guinea", dial_code: "+675", iso2: "pg", flagUrl: "https://flagcdn.com/pg.svg" },
  { name: "Paraguay", dial_code: "+595", iso2: "py", flagUrl: "https://flagcdn.com/py.svg" },
  { name: "Peru", dial_code: "+51", iso2: "pe", flagUrl: "https://flagcdn.com/pe.svg" },
  { name: "Philippines", dial_code: "+63", iso2: "ph", flagUrl: "https://flagcdn.com/ph.svg" },
  { name: "Poland", dial_code: "+48", iso2: "pl", flagUrl: "https://flagcdn.com/pl.svg" },
  { name: "Portugal", dial_code: "+351", iso2: "pt", flagUrl: "https://flagcdn.com/pt.svg" },
  { name: "Qatar", dial_code: "+974", iso2: "qa", flagUrl: "https://flagcdn.com/qa.svg" },
  { name: "Romania", dial_code: "+40", iso2: "ro", flagUrl: "https://flagcdn.com/ro.svg" },
  { name: "Russia", dial_code: "+7", iso2: "ru", flagUrl: "https://flagcdn.com/ru.svg" },
  { name: "Rwanda", dial_code: "+250", iso2: "rw", flagUrl: "https://flagcdn.com/rw.svg" },
  { name: "Saint Kitts and Nevis", dial_code: "+1-869", iso2: "kn", flagUrl: "https://flagcdn.com/kn.svg" },
  { name: "Saint Lucia", dial_code: "+1-758", iso2: "lc", flagUrl: "https://flagcdn.com/lc.svg" },
  { name: "Saint Vincent and the Grenadines", dial_code: "+1-784", iso2: "vc", flagUrl: "https://flagcdn.com/vc.svg" },
  { name: "Samoa", dial_code: "+685", iso2: "ws", flagUrl: "https://flagcdn.com/ws.svg" },
  { name: "San Marino", dial_code: "+378", iso2: "sm", flagUrl: "https://flagcdn.com/sm.svg" },
  { name: "Sao Tome and Principe", dial_code: "+239", iso2: "st", flagUrl: "https://flagcdn.com/st.svg" },
  { name: "Saudi Arabia", dial_code: "+966", iso2: "sa", flagUrl: "https://flagcdn.com/sa.svg" },
  { name: "Senegal", dial_code: "+221", iso2: "sn", flagUrl: "https://flagcdn.com/sn.svg" },
  { name: "Serbia", dial_code: "+381", iso2: "rs", flagUrl: "https://flagcdn.com/rs.svg" },
  { name: "Seychelles", dial_code: "+248", iso2: "sc", flagUrl: "https://flagcdn.com/sc.svg" },
  { name: "Sierra Leone", dial_code: "+232", iso2: "sl", flagUrl: "https://flagcdn.com/sl.svg" },
  { name: "Singapore", dial_code: "+65", iso2: "sg", flagUrl: "https://flagcdn.com/sg.svg" },
  { name: "Slovakia", dial_code: "+421", iso2: "sk", flagUrl: "https://flagcdn.com/sk.svg" },
  { name: "Slovenia", dial_code: "+386", iso2: "si", flagUrl: "https://flagcdn.com/si.svg" },
  { name: "Solomon Islands", dial_code: "+677", iso2: "sb", flagUrl: "https://flagcdn.com/sb.svg" },
  { name: "Somalia", dial_code: "+252", iso2: "so", flagUrl: "https://flagcdn.com/so.svg" },
  { name: "South Africa", dial_code: "+27", iso2: "za", flagUrl: "https://flagcdn.com/za.svg" },
  { name: "South Korea", dial_code: "+82", iso2: "kr", flagUrl: "https://flagcdn.com/kr.svg" },
  { name: "South Sudan", dial_code: "+211", iso2: "ss", flagUrl: "https://flagcdn.com/ss.svg" },
  { name: "Spain", dial_code: "+34", iso2: "es", flagUrl: "https://flagcdn.com/es.svg" },
  { name: "Sri Lanka", dial_code: "+94", iso2: "lk", flagUrl: "https://flagcdn.com/lk.svg" },
  { name: "Sudan", dial_code: "+249", iso2: "sd", flagUrl: "https://flagcdn.com/sd.svg" },
  { name: "Suriname", dial_code: "+597", iso2: "sr", flagUrl: "https://flagcdn.com/sr.svg" },
  { name: "Sweden", dial_code: "+46", iso2: "se", flagUrl: "https://flagcdn.com/se.svg" },
  { name: "Switzerland", dial_code: "+41", iso2: "ch", flagUrl: "https://flagcdn.com/ch.svg" },
  { name: "Syria", dial_code: "+963", iso2: "sy", flagUrl: "https://flagcdn.com/sy.svg" },
  { name: "Taiwan", dial_code: "+886", iso2: "tw", flagUrl: "https://flagcdn.com/tw.svg" },
  { name: "Tajikistan", dial_code: "+992", iso2: "tj", flagUrl: "https://flagcdn.com/tj.svg" },
  { name: "Tanzania", dial_code: "+255", iso2: "tz", flagUrl: "https://flagcdn.com/tz.svg" },
  { name: "Thailand", dial_code: "+66", iso2: "th", flagUrl: "https://flagcdn.com/th.svg" },
  { name: "Togo", dial_code: "+228", iso2: "tg", flagUrl: "https://flagcdn.com/tg.svg" },
  { name: "Tonga", dial_code: "+676", iso2: "to", flagUrl: "https://flagcdn.com/to.svg" },
  { name: "Trinidad and Tobago", dial_code: "+1-868", iso2: "tt", flagUrl: "https://flagcdn.com/tt.svg" },
  { name: "Tunisia", dial_code: "+216", iso2: "tn", flagUrl: "https://flagcdn.com/tn.svg" },
  { name: "Turkey", dial_code: "+90", iso2: "tr", flagUrl: "https://flagcdn.com/tr.svg" },
  { name: "Turkmenistan", dial_code: "+993", iso2: "tm", flagUrl: "https://flagcdn.com/tm.svg" },
  { name: "Tuvalu", dial_code: "+688", iso2: "tv", flagUrl: "https://flagcdn.com/tv.svg" },
  { name: "Uganda", dial_code: "+256", iso2: "ug", flagUrl: "https://flagcdn.com/ug.svg" },
  { name: "Ukraine", dial_code: "+380", iso2: "ua", flagUrl: "https://flagcdn.com/ua.svg" },
  { name: "United Arab Emirates", dial_code: "+971", iso2: "ae", flagUrl: "https://flagcdn.com/ae.svg" },
  { name: "United Kingdom", dial_code: "+44", iso2: "gb", flagUrl: "https://flagcdn.com/gb.svg" },
  { name: "United States", dial_code: "+1", iso2: "us", flagUrl: "https://flagcdn.com/us.svg" },
  { name: "Uruguay", dial_code: "+598", iso2: "uy", flagUrl: "https://flagcdn.com/uy.svg" },
  { name: "Uzbekistan", dial_code: "+998", iso2: "uz", flagUrl: "https://flagcdn.com/uz.svg" },
  { name: "Vanuatu", dial_code: "+678", iso2: "vu", flagUrl: "https://flagcdn.com/vu.svg" },
  { name: "Vatican City", dial_code: "+379", iso2: "va", flagUrl: "https://flagcdn.com/va.svg" },
  { name: "Venezuela", dial_code: "+58", iso2: "ve", flagUrl: "https://flagcdn.com/ve.svg" },
  { name: "Vietnam", dial_code: "+84", iso2: "vn", flagUrl: "https://flagcdn.com/vn.svg" },
  { name: "Yemen", dial_code: "+967", iso2: "ye", flagUrl: "https://flagcdn.com/ye.svg" },
  { name: "Zambia", dial_code: "+260", iso2: "zm", flagUrl: "https://flagcdn.com/zm.svg" },
  { name: "Zimbabwe", dial_code: "+263", iso2: "zw", flagUrl: "https://flagcdn.com/zw.svg" },
]
